### ISSUE TITLE
Does not run — SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dikonov** [magicgoose/simple_dr_meter#2]
Trying to run this dr meter results in the error:

$ ./main.py
  File "./main.py", line 27
    performers: Iterable[str]
              ^
SyntaxError: invalid syntax

What does that mean? It leaves me clueless how to start this  app. I do have python, pythin-numpy and python-chardet installed.

**Comment by magicgoose** [comment]
Please try running `python3 --version` and post the output here.
I bet you are using an old version; project README says the minimum is 3.6.

**Comment by magicgoose** [comment]
@dikonov that's sad, but 3.5 support is currently not a goal.
Hopefully they will catch up soon, as 3.6 was released in year 2016.
Or you can edit the code by removing 3.6 specific features, there aren't too much of them IIRC.
