### ISSUE TITLE
Another 3.6-ism?

### ISSUE THREAD

**Issue by dikonov** [magicgoose/simple_dr_meter#3]
I tried to backport this to python 3.51 (I cannot run 3.6 here) and after fixing most issues encounter this:

$ ./main.py
Traceback (most recent call last):
  File "./main.py", line 12, in <module>
    from audio_io import read_audio_info, read_audio_data
  File "/home/slava/Загрузки/2/simple_dr_meter-master_3.51/audio_io/__init__.py", line 1, in <module>
    from audio_io.audio_io import *
  File "/home/slava/Загрузки/2/simple_dr_meter-master_3.51/audio_io/audio_io.py", line 23, in <module>
    from enum import Enum, auto
ImportError: cannot import name 'auto'

Is it another syntax problem or a code problem? 

[allpython.diff.txt](https://github.com/magicgoose/simple_dr_meter/files/1934908/allpython.diff.txt)
I attach an almost ready patch to run in python 3.51.

**Comment by magicgoose** [comment]
@dikonov 
`enum.auto` is new in Python 3.6:
https://docs.python.org/3/library/enum.html#enum.auto

**Comment by magicgoose** [comment]
@dikonov 
патч выглядит в основном жизнеспособно, но, как я понял, он убирает форматирование чисел в функции форматирования лога. (количество знаков после точки, и т.д.)

**Comment by dikonov** [comment]
Я просто не знаю питон и не понял еще, как это форматирование сохранить. Perl роднее и проще. 

Еще я недоволен непродуктивным размножением питонов даже в ужатой системе моего медиапроигрывателя. Зависимости разных пакетов тянут по две разные версии и кучу модулей для каждой.

**Comment by magicgoose** [comment]
Может быть, сделаю совместимость с 3.5, если нечем заняться будет.

> Еще я недоволен непродуктивным размножением питонов даже в ужатой системе моего медиапроигрывателя. **Зависимости разных пакетов тянут по две разные версии и кучу модулей для каждой.**

Наверное, это всё-таки уже к авторам дистрибутива.
